plugins:
  lottery_enabled:
    default: true
    client: true
  lottery_min_participants_global:
    default: 5
    min: 1
    client: true
  lottery_post_lock_delay_minutes:
    default: 10
    min: 0
  lottery_excluded_groups:
    type: group_list
    default: ""
